<?php
/**
 * Content shipped with the theme, generated from src/data by build-wp.js.
 * Imported once on activation. Do not edit by hand: edit the content in
 * wp-admin instead, which is the point of the import.
 *
 * @package absolute-zero
 */

defined( 'ABSPATH' ) || exit;

function az_seed_data() {
	return array(
		'pages' => array(
			array(
				'slug' => 'home',
				'title' => 'Home',
				'front' => true,
				'order' => 0,
			),
			array(
				'slug' => 'mission-and-vision',
				'title' => 'Mission and Vision',
				'front' => false,
				'order' => 1,
			),
			array(
				'slug' => 'our-team',
				'title' => 'Our Team',
				'front' => false,
				'order' => 2,
			),
			array(
				'slug' => 'build-and-program',
				'title' => 'Build and Program',
				'front' => false,
				'order' => 3,
			),
			array(
				'slug' => 'outreach',
				'title' => 'Outreach',
				'front' => false,
				'order' => 4,
			),
			array(
				'slug' => 'sponsors-and-donors',
				'title' => 'Sponsors and Donors',
				'front' => false,
				'order' => 5,
			),
			array(
				'slug' => 'contact',
				'title' => 'Contact',
				'front' => false,
				'order' => 6,
			),
		),
		'menus' => array(
			'primary' => array(
				array(
					'label' => 'Home',
					'title' => 'Home',
					'path' => '/',
				),
				array(
					'label' => 'Mission',
					'title' => 'Mission and Vision',
					'path' => '/mission-and-vision/',
				),
				array(
					'label' => 'Team',
					'title' => 'Our Team',
					'path' => '/our-team/',
				),
				array(
					'label' => 'Build',
					'title' => 'Build and Program',
					'path' => '/build-and-program/',
				),
				array(
					'label' => 'Outreach',
					'title' => 'Outreach',
					'path' => '/outreach/',
				),
				array(
					'label' => 'Sponsors',
					'title' => 'Sponsors and Donors',
					'path' => '/sponsors-and-donors/',
				),
				array(
					'label' => 'Contact',
					'title' => 'Contact',
					'path' => '/contact/',
				),
			),
			'footer' => array(
				array(
					'label' => 'Mission and Vision',
					'path' => '/mission-and-vision/',
				),
				array(
					'label' => 'Our Team',
					'path' => '/our-team/',
				),
				array(
					'label' => 'Build and Program',
					'path' => '/build-and-program/',
				),
				array(
					'label' => 'Outreach',
					'path' => '/outreach/',
				),
				array(
					'label' => 'Sponsors and Donors',
					'path' => '/sponsors-and-donors/',
				),
				array(
					'label' => 'Contact',
					'path' => '/contact/',
				),
			),
			'teams' => array(
				array(
					'label' => 'Open Access library',
					'path' => '/outreach/open-access/',
				),
				array(
					'label' => 'Collaboration Summit',
					'path' => '/outreach/ftc-collaboration-summit/',
				),
				array(
					'label' => 'Book a workshop',
					'path' => '/outreach/',
				),
			),
		),
		'seasons' => array(
			array(
				'slug' => 'biobuzz',
				'name' => 'BIOBUZZ',
				'description' => '2026-2027',
				'order' => 0,
			),
			array(
				'slug' => 'decode',
				'name' => 'DECODE',
				'description' => '2025-2026',
				'order' => 1,
			),
			array(
				'slug' => 'centerstage',
				'name' => 'CENTERSTAGE',
				'description' => '2023-2024',
				'order' => 2,
			),
			array(
				'slug' => 'earlier',
				'name' => 'Earlier',
				'description' => '2017-2023',
				'order' => 3,
			),
		),
		'programs' => array(
			array(
				'slug' => 'ftc-collaboration-summit',
				'title' => 'FTC Collaboration Summit',
				'blurb' => 'A working day for area FTC teams: shared field time, honest feedback, and a notebook exchange before qualifiers.',
				'featured' => false,
				'order' => 0,
			),
			array(
				'slug' => 'robo-reach',
				'title' => 'Robo Reach',
				'blurb' => 'A free match score prediction tool we built for every FTC team. Power ratings, per-match predictions and live event tracking.',
				'featured' => true,
				'order' => 1,
			),
			array(
				'slug' => 'classes-with-curie',
				'title' => 'Classes with Curie',
				'blurb' => 'A robotics course we run with Curie Learning, built around the FIRST progression from LEGO to FTC.',
				'featured' => true,
				'order' => 2,
			),
			array(
				'slug' => 'best-brains',
				'title' => 'Best Brains',
				'blurb' => 'Introductory robotics and coding sessions for the 8 to 14 age group at Best Brains centres across Loudoun County.',
				'featured' => false,
				'order' => 3,
			),
			array(
				'slug' => 'run4charity',
				'title' => 'Run4Charity 5K',
				'blurb' => 'We volunteer at the Best Runners charity race in Aldie and run a robotics table at the finish line.',
				'featured' => false,
				'order' => 4,
			),
			array(
				'slug' => 'techstravaganza',
				'title' => 'Techstravaganza',
				'blurb' => 'The free public STEM fair at Thomas Jefferson High School. We have been running a booth there since 2018.',
				'featured' => true,
				'order' => 5,
			),
			array(
				'slug' => 'namma-bhoomi',
				'title' => 'Namma Bhoomi',
				'blurb' => 'Robotics kits and remote instruction for a residential school for working children in Karnataka, India.',
				'featured' => false,
				'order' => 6,
			),
			array(
				'slug' => 'open-access',
				'title' => 'Open Access',
				'blurb' => 'Our engineering notebooks, pit designs and build guides, published for any team that wants them.',
				'featured' => false,
				'order' => 7,
			),
		),
		'workshops' => array(
			array(
				'slug' => 'loudoun-library-series-autumn-block-biobuzz',
				'title' => 'Loudoun library series, autumn block',
				'season' => 'biobuzz',
				'venue' => 'Ashburn, Cascades and Gum Spring libraries',
				'date' => 'Autumn 2026',
				'dateISO' => '',
				'audience' => 'Ages 7 to 13',
				'planned' => true,
				'summary' => 'A three-stop return of the library series. Each session opens with a driving slot on the competition robot, then moves to a build challenge using the same design loop we use on the real machine.',
				'detail' => '',
				'plan' => 'Drive the BIOBUZZ robot on a scoring element
Take apart a mechanism and explain what each part does
Build and test one intake concept against a timer',
				'video' => '',
				'order' => 0,
			),
			array(
				'slug' => 'ftc-collaboration-summit-biobuzz',
				'title' => 'FTC Collaboration Summit',
				'season' => 'biobuzz',
				'venue' => 'To be confirmed',
				'date' => 'Pre-qualifier, winter 2026',
				'dateISO' => '',
				'audience' => 'Area FTC teams',
				'planned' => true,
				'summary' => 'Shared practice field, a structured feedback round on each robot, and a notebook exchange before the first qualifier of the season.',
				'detail' => '',
				'plan' => 'Timed practice matches between attending teams
Twenty-minute design review per robot, run by a mixed panel
Engineering notebook swap and written feedback',
				'video' => '',
				'order' => 1,
			),
			array(
				'slug' => 'classes-with-curie-biobuzz',
				'title' => 'Classes with Curie',
				'season' => 'biobuzz',
				'venue' => 'Curie Learning, Ashburn',
				'date' => 'Term dates to be confirmed',
				'dateISO' => '',
				'audience' => 'Ages 9 to 14',
				'planned' => true,
				'summary' => 'A short robotics course taught by our students, built around the FIRST progression from LEGO-based robotics into FTC.',
				'detail' => '',
				'plan' => 'Session one: what a robot actually is, and the design loop
Session two: drivetrains, gearing and why it matters
Session three: sensors and the first line of code
Session four: a scored challenge run as a mini-competition',
				'video' => '',
				'order' => 2,
			),
			array(
				'slug' => 'best-brains-introductory-robotics-biobuzz',
				'title' => 'Best Brains introductory robotics',
				'season' => 'biobuzz',
				'venue' => 'Best Brains, Loudoun County centres',
				'date' => 'Term dates to be confirmed',
				'dateISO' => '',
				'audience' => 'Ages 8 to 14',
				'planned' => true,
				'summary' => 'Introductory robotics and block-coding sessions for students who have not met FIRST before, pitched at the age group Best Brains already serves.',
				'detail' => '',
				'plan' => 'Block coding on a small drivable robot
A build-and-test challenge with a fixed parts budget
What FIRST LEGO League looks like, and how to join one',
				'video' => '',
				'order' => 3,
			),
			array(
				'slug' => 'techstravaganza-2027-biobuzz',
				'title' => 'Techstravaganza 2027',
				'season' => 'biobuzz',
				'venue' => 'Thomas Jefferson High School for Science and Technology, Alexandria',
				'date' => 'May 2027',
				'dateISO' => '',
				'audience' => 'Open to the public',
				'planned' => true,
				'summary' => 'A booth at the free public STEM fair run by TWIST. We bring the competition robot and a driver station and let visitors take the controls.',
				'detail' => '',
				'plan' => 'Open driving on the competition robot
A LEGO-based build table for younger visitors
A short talk on how to start an FTC team',
				'video' => '',
				'order' => 4,
			),
			array(
				'slug' => 'run4charity-biobuzz',
				'title' => 'Run4Charity',
				'season' => 'biobuzz',
				'venue' => 'Aldie, Virginia',
				'date' => 'September 2026',
				'dateISO' => '',
				'audience' => 'Community event',
				'planned' => true,
				'summary' => 'Volunteering at the Best Runners charity race, and running a robotics table near the finish line for families waiting on runners.',
				'detail' => '',
				'plan' => 'Course marshalling and registration support
A robot demo table at the finish area',
				'video' => '',
				'order' => 5,
			),
			array(
				'slug' => 'ashburn-library-workshop-decode',
				'title' => 'Ashburn Library workshop',
				'season' => 'decode',
				'venue' => 'Ashburn Library',
				'date' => 'March 2026',
				'dateISO' => '2026-03-28',
				'audience' => 'Ages 7 to 13',
				'planned' => false,
				'summary' => 'Visitors operated a real competition robot and got a first look at what FIRST robotics involves.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 6,
			),
			array(
				'slug' => 'cascades-library-workshop-decode',
				'title' => 'Cascades Library workshop',
				'season' => 'decode',
				'venue' => 'Cascades Library',
				'date' => 'March 2026',
				'dateISO' => '2026-03-21',
				'audience' => 'Ages 7 to 13',
				'planned' => false,
				'summary' => 'A session built around the engineering design process rather than the finished robot.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 7,
			),
			array(
				'slug' => 'cascades-library-series-decode',
				'title' => 'Cascades Library series',
				'season' => 'decode',
				'venue' => 'Cascades Library',
				'date' => '2025 to 2026',
				'dateISO' => '2026-02-01',
				'audience' => 'Ages 7 to 13',
				'planned' => false,
				'summary' => 'A recurring block of hands-on robotics sessions across the season.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 8,
			),
			array(
				'slug' => 'gum-spring-library-series-decode',
				'title' => 'Gum Spring Library series',
				'season' => 'decode',
				'venue' => 'Gum Spring Library',
				'date' => '2025 to 2026',
				'dateISO' => '2026-02-15',
				'audience' => 'Ages 7 to 13',
				'planned' => false,
				'summary' => 'The same series, run for a second branch and a second set of families.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 9,
			),
			array(
				'slug' => 'girl-scouts-troop-meet-up-centerstage',
				'title' => 'Girl Scouts troop meet-up',
				'season' => 'centerstage',
				'venue' => 'Local Girl Scout troop',
				'date' => 'January 2024',
				'dateISO' => '2024-01-24',
				'audience' => 'Girl Scout troop',
				'planned' => false,
				'summary' => 'An introduction to FTC for a local troop, ending with a complete robot the troop had built together.',
				'detail' => '',
				'plan' => '',
				'video' => 'https://www.youtube.com/watch?v=-4qR3eIjdy4',
				'order' => 10,
			),
			array(
				'slug' => 'robot-build-and-programming-guides-earlier',
				'title' => 'Robot build and programming guides',
				'season' => 'earlier',
				'venue' => 'Published online',
				'date' => 'January 2022',
				'dateISO' => '2022-01-09',
				'audience' => 'Rookie teams',
				'planned' => false,
				'summary' => 'Five new members each wrote a guide covering what they had just learned about building and programming a robot, so the next rookie would not start from nothing.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 11,
			),
			array(
				'slug' => 'world-robot-olympiad-preparation-workshops-earlier',
				'title' => 'World Robot Olympiad preparation workshops',
				'season' => 'earlier',
				'venue' => 'Online',
				'date' => 'April to May 2020',
				'dateISO' => '2020-05-04',
				'audience' => 'WRO competitors',
				'planned' => false,
				'summary' => 'Four weeks of online workshops for students preparing EV3 challenges for the 2020 WRO season, covering game strategy and open question time. The presentations were streamed on the team\'s YouTube channel.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 12,
			),
			array(
				'slug' => 'algonkian-elementary-stem-showcase-earlier',
				'title' => 'Algonkian Elementary STEM showcase',
				'season' => 'earlier',
				'venue' => 'Algonkian Elementary School',
				'date' => 'February 2020',
				'dateISO' => '2020-02-26',
				'audience' => 'Elementary school',
				'planned' => false,
				'summary' => 'A returning invitation to the school\'s annual STEM showcase, presenting FTC alongside the other Robotics for Youth programmes.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 13,
			),
			array(
				'slug' => 'absolute-zero-scrimmage-earlier',
				'title' => 'Absolute Zero scrimmage',
				'season' => 'earlier',
				'venue' => 'Hosted by Absolute Zero',
				'date' => 'February 2020',
				'dateISO' => '2020-02-15',
				'audience' => 'Nine FTC teams',
				'planned' => false,
				'summary' => 'We hosted nine FTC teams for a full scrimmage with a real match schedule, so everyone got competition reps before states.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 14,
			),
			array(
				'slug' => 'haymaker-steam-expo-earlier',
				'title' => 'Haymaker STEAM Expo',
				'season' => 'earlier',
				'venue' => 'Battlefield High School',
				'date' => 'January 2020',
				'dateISO' => '2020-01-25',
				'audience' => 'Open to the public',
				'planned' => false,
				'summary' => 'Demonstrations of drones, a secondary robot, a Raspberry Pi arcade and EV3 kits, volunteering alongside FRC team ILITE.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 15,
			),
			array(
				'slug' => 'six-team-scrimmage-earlier',
				'title' => 'Six-team scrimmage',
				'season' => 'earlier',
				'venue' => 'Hosted by Xtreme Voltage 10515',
				'date' => 'January 2020',
				'dateISO' => '2020-01-25',
				'audience' => 'Six FTC teams',
				'planned' => false,
				'summary' => 'A shared practice day with five other teams, focused on trading ideas rather than winning matches.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 16,
			),
			array(
				'slug' => 'collaboration-with-slice-of-pi-13441-earlier',
				'title' => 'Collaboration with Slice of Pi 13441',
				'season' => 'earlier',
				'venue' => 'Robotics for Youth',
				'date' => 'January 2020',
				'dateISO' => '2020-01-04',
				'audience' => 'One FTC team',
				'planned' => false,
				'summary' => 'A practice and feedback exchange with a fellow Robotics for Youth team before their first qualifier.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 17,
			),
			array(
				'slug' => 'scrimmage-with-swat-team-16502-earlier',
				'title' => 'Scrimmage with SWAT Team 16502',
				'season' => 'earlier',
				'venue' => 'Hosted by Absolute Zero',
				'date' => 'December 2019',
				'dateISO' => '2019-12-13',
				'audience' => 'One FTC team',
				'planned' => false,
				'summary' => 'Alliance practice with a focus on scoring accuracy and driver communication between matches.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 18,
			),
			array(
				'slug' => 'onbot-java-presentation-earlier',
				'title' => 'OnBot Java presentation',
				'season' => 'earlier',
				'venue' => 'ECPI University',
				'date' => 'September 2019',
				'dateISO' => '2019-09-21',
				'audience' => 'Rookie FTC teams',
				'planned' => false,
				'summary' => 'Our second year giving this presentation. A year of extra season experience made the advice considerably more useful than the first time.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 19,
			),
			array(
				'slug' => 'mentoring-the-gearbox-gators-earlier',
				'title' => 'Mentoring the Gearbox Gators',
				'season' => 'earlier',
				'venue' => 'Rookie team visit',
				'date' => 'December 2018',
				'dateISO' => '2018-12-01',
				'audience' => 'One rookie FTC team',
				'planned' => false,
				'summary' => 'Driving practice, wiring cleanup and engineering notebook advice for a rookie team days before their qualifier.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 20,
			),
			array(
				'slug' => 'nasa-moon-to-mars-live-show-earlier',
				'title' => 'NASA Moon to Mars live show',
				'season' => 'earlier',
				'venue' => 'NASA Headquarters, Washington DC',
				'date' => 'November 2018',
				'dateISO' => '2018-11-29',
				'audience' => 'Press and public',
				'planned' => false,
				'summary' => 'Invited to explain FIRST programmes at a NASA news conference on the return to the Moon.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 21,
			),
			array(
				'slug' => 'first-lego-league-refereeing-earlier',
				'title' => 'FIRST LEGO League refereeing',
				'season' => 'earlier',
				'venue' => 'Mary Ellen Henderson regional',
				'date' => 'November 2018',
				'dateISO' => '2018-11-10',
				'audience' => 'FLL competitors',
				'planned' => false,
				'summary' => 'Three team members refereed a regional FLL competition, which turned out to be the clearest lesson in the FIRST core values any of us had had.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 22,
			),
			array(
				'slug' => 'star-wars-reads-earlier',
				'title' => 'Star Wars Reads',
				'season' => 'earlier',
				'venue' => 'Community event',
				'date' => 'November 2018',
				'dateISO' => '2018-11-03',
				'audience' => 'Families',
				'planned' => false,
				'summary' => 'A scrimmage, a demo robot for visitors to drive and an EV3 programming station, run with FLL team Cascades Thunderbots.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 23,
			),
			array(
				'slug' => 'minefaire-expo-earlier',
				'title' => 'MineFaire Expo',
				'season' => 'earlier',
				'venue' => 'MineFaire',
				'date' => 'October 2018',
				'dateISO' => '2018-10-06',
				'audience' => 'Open to the public',
				'planned' => false,
				'summary' => 'A second year at the expo. Robot demos, mBot soccer and EV3 programming, aimed squarely at raising awareness of FLL.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 24,
			),
			array(
				'slug' => 'stem-in-30-earlier',
				'title' => 'STEM in 30',
				'season' => 'earlier',
				'venue' => 'National Air and Space Museum',
				'date' => 'September 2018',
				'dateISO' => '2018-09-05',
				'audience' => 'Broadcast audience',
				'planned' => false,
				'summary' => 'Team members were invited onto the museum\'s educational programme to talk about FIRST LEGO League. The episode was recorded and aired.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 25,
			),
			array(
				'slug' => 'techstravaganza-earlier',
				'title' => 'Techstravaganza',
				'season' => 'earlier',
				'venue' => 'Thomas Jefferson High School for Science and Technology',
				'date' => 'May 2018',
				'dateISO' => '2018-05-19',
				'audience' => 'Open to the public',
				'planned' => false,
				'summary' => 'We taught visitors the Mindstorms programming language and gave them a working understanding of EV3 robots.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 26,
			),
			array(
				'slug' => 'usa-science-and-engineering-festival-earlier',
				'title' => 'USA Science and Engineering Festival',
				'season' => 'earlier',
				'venue' => 'Washington DC',
				'date' => 'April 2018',
				'dateISO' => '2018-04-07',
				'audience' => 'Open to the public',
				'planned' => false,
				'summary' => 'FIRST invited us to display and run our robot at the festival across two days, with a booth and a demo robot visitors could drive.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 27,
			),
			array(
				'slug' => 'world-robot-olympiad-regional-tournament-earlier',
				'title' => 'World Robot Olympiad regional tournament',
				'season' => 'earlier',
				'venue' => 'Regional tournament',
				'date' => '2018',
				'dateISO' => '2018-05-01',
				'audience' => 'Open to the public',
				'planned' => false,
				'summary' => 'Workshops, tutorials and hands-on robot demonstrations at a regional WRO tournament attended by over five hundred people.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 28,
			),
			array(
				'slug' => 'haymaker-expo-earlier',
				'title' => 'Haymaker Expo',
				'season' => 'earlier',
				'venue' => 'Battlefield High School',
				'date' => 'January 2018',
				'dateISO' => '2018-01-27',
				'audience' => 'Open to the public',
				'planned' => false,
				'summary' => 'An FTC station with hands-on demos for more than fifty children, with a plexiglass panel added to the robot so our sponsors travelled with it.',
				'detail' => '',
				'plan' => '',
				'video' => '',
				'order' => 29,
			),
		),
		'members' => array(
			array(
				'slug' => 'coach-dinesh',
				'title' => 'Coach Dinesh',
				'group' => 'coach',
				'roles' => array(),
				'line' => 'Software developer, and a board member of Robotics for Youth.',
				'bio' => 'Has coached Absolute Zero since the team\'s early seasons. Spends most of a build season asking students the question behind the question rather than answering the first one.',
				'stale' => true,
				'order' => 0,
			),
			array(
				'slug' => 'coach-saji',
				'title' => 'Coach Saji',
				'group' => 'coach',
				'roles' => array(),
				'line' => 'Software engineer, and a board member of Robotics for Youth.',
				'bio' => 'Coached FLL team 1540 for four seasons before joining Absolute Zero, and still runs the introductory sessions that bring middle schoolers into FIRST.',
				'stale' => true,
				'order' => 1,
			),
			array(
				'slug' => 'amit',
				'title' => 'Amit',
				'group' => 'student',
				'roles' => array(
					'cad',
					'build',
				),
				'line' => 'CAD and mechanical design',
				'bio' => '',
				'stale' => false,
				'order' => 0,
			),
			array(
				'slug' => 'vishishya',
				'title' => 'Vishishya',
				'group' => 'student',
				'roles' => array(
					'build',
				),
				'line' => 'Mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 1,
			),
			array(
				'slug' => 'gaurav',
				'title' => 'Gaurav',
				'group' => 'student',
				'roles' => array(
					'build',
					'drive',
				),
				'line' => 'Mechanical build, driver',
				'bio' => '',
				'stale' => false,
				'order' => 2,
			),
			array(
				'slug' => 'keerthana',
				'title' => 'Keerthana',
				'group' => 'student',
				'roles' => array(
					'build',
					'outreach',
				),
				'line' => 'Mechanical build, outreach lead',
				'bio' => '',
				'stale' => false,
				'order' => 3,
			),
			array(
				'slug' => 'nabhya',
				'title' => 'Nabhya',
				'group' => 'student',
				'roles' => array(
					'build',
				),
				'line' => 'Mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 4,
			),
			array(
				'slug' => 'sumukh',
				'title' => 'Sumukh',
				'group' => 'student',
				'roles' => array(
					'outreach',
					'build',
				),
				'line' => 'Outreach, mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 5,
			),
			array(
				'slug' => 'anirudh',
				'title' => 'Anirudh',
				'group' => 'student',
				'roles' => array(
					'build',
				),
				'line' => 'Mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 6,
			),
			array(
				'slug' => 'eshanth',
				'title' => 'Eshanth',
				'group' => 'student',
				'roles' => array(
					'build',
					'program',
				),
				'line' => 'Mechanical build, programming',
				'bio' => '',
				'stale' => false,
				'order' => 7,
			),
			array(
				'slug' => 'prisha',
				'title' => 'Prisha',
				'group' => 'student',
				'roles' => array(
					'build',
					'outreach',
				),
				'line' => 'Mechanical build, outreach',
				'bio' => '',
				'stale' => false,
				'order' => 8,
			),
			array(
				'slug' => 'neeva',
				'title' => 'Neeva',
				'group' => 'student',
				'roles' => array(
					'outreach',
				),
				'line' => 'Outreach',
				'bio' => '',
				'stale' => false,
				'order' => 9,
			),
			array(
				'slug' => 'cheytna',
				'title' => 'Cheytna',
				'group' => 'student',
				'roles' => array(
					'outreach',
					'build',
				),
				'line' => 'Outreach, mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 10,
			),
			array(
				'slug' => 'goutam',
				'title' => 'Goutam',
				'group' => 'student',
				'roles' => array(
					'outreach',
					'program',
				),
				'line' => 'Outreach, programming',
				'bio' => '',
				'stale' => false,
				'order' => 11,
			),
			array(
				'slug' => 'sreehitha',
				'title' => 'Sreehitha',
				'group' => 'student',
				'roles' => array(
					'build',
				),
				'line' => 'Mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 12,
			),
			array(
				'slug' => 'kunwoo',
				'title' => 'Kunwoo',
				'group' => 'student',
				'roles' => array(
					'build',
				),
				'line' => 'Mechanical build',
				'bio' => '',
				'stale' => false,
				'order' => 13,
			),
			array(
				'slug' => 'nikitha',
				'title' => 'Nikitha',
				'group' => 'student',
				'roles' => array(
					'outreach',
				),
				'line' => 'Outreach',
				'bio' => '',
				'stale' => false,
				'order' => 14,
			),
			array(
				'slug' => 'haresh-umaretiya',
				'title' => 'Haresh Umaretiya',
				'group' => 'mentor',
				'roles' => array(),
				'line' => 'Co-founder, Astute Engineering.',
				'bio' => 'Reviews mechanism concepts with the build sub-team and pushes hard on tolerances and manufacturability.',
				'stale' => false,
				'order' => 0,
			),
			array(
				'slug' => 'giri-tanguturi',
				'title' => 'Giri Tanguturi',
				'group' => 'mentor',
				'roles' => array(),
				'line' => 'Electrical engineer. Tesla, previously Sun Microsystems.',
				'bio' => 'Works with the team on wiring discipline, power budgeting and the electrical section of the engineering notebook.',
				'stale' => false,
				'order' => 1,
			),
		),
		'roles' => array(
			array(
				'slug' => 'build',
				'name' => 'Build',
				'order' => 0,
			),
			array(
				'slug' => 'program',
				'name' => 'Programming',
				'order' => 1,
			),
			array(
				'slug' => 'outreach',
				'name' => 'Outreach',
				'order' => 2,
			),
			array(
				'slug' => 'drive',
				'name' => 'Drive team',
				'order' => 3,
			),
			array(
				'slug' => 'cad',
				'name' => 'CAD',
				'order' => 4,
			),
		),
		'groups' => array(
			array(
				'slug' => 'coach',
				'name' => 'Coaches',
				'order' => 0,
			),
			array(
				'slug' => 'student',
				'name' => 'Students',
				'order' => 1,
			),
			array(
				'slug' => 'mentor',
				'name' => 'Mentors',
				'order' => 2,
			),
		),
		'sponsors' => array(
			array(
				'slug' => 'fannie-mae',
				'title' => 'Fannie Mae',
				'url' => '',
				'kind' => 'Corporate',
				'order' => 0,
			),
			array(
				'slug' => 'leidos',
				'title' => 'Leidos',
				'url' => 'https://www.leidos.com/',
				'kind' => 'Corporate',
				'order' => 1,
			),
			array(
				'slug' => 'robotics-for-youth',
				'title' => 'Robotics for Youth',
				'url' => 'https://roboticsforyouth.org/',
				'kind' => 'Parent nonprofit',
				'order' => 2,
			),
			array(
				'slug' => 'curie-learning',
				'title' => 'Curie Learning',
				'url' => 'https://curielearning.com/',
				'kind' => 'Program partner',
				'order' => 3,
			),
			array(
				'slug' => 'best-brains',
				'title' => 'Best Brains',
				'url' => 'https://bestbrains.com/',
				'kind' => 'Program partner',
				'order' => 4,
			),
			array(
				'slug' => 'best-runners',
				'title' => 'Best Runners',
				'url' => 'https://www.bestrunners.org/',
				'kind' => 'Community partner',
				'order' => 5,
			),
			array(
				'slug' => 'first',
				'title' => 'FIRST',
				'url' => 'https://www.firstinspires.org/',
				'kind' => 'Program',
				'order' => 6,
			),
		),
		'tiers' => array(
			array(
				'slug' => 'platinum',
				'name' => 'Platinum',
				'amount' => '$1,500 and above',
				'description' => 'Logo on the robot and on team apparel
Logo on the team banner, displayed at every competition
Named on this page
A thank-you post across our social channels',
				'order' => 0,
			),
			array(
				'slug' => 'gold',
				'name' => 'Gold',
				'amount' => '$1,000 to $1,499',
				'description' => 'Logo on team apparel
Logo on the team banner
Named on this page
A thank-you post across our social channels',
				'order' => 1,
			),
			array(
				'slug' => 'silver',
				'name' => 'Silver',
				'amount' => '$500 to $999',
				'description' => 'Logo on the team banner
Named on this page
A thank-you post across our social channels',
				'order' => 2,
			),
			array(
				'slug' => 'bronze',
				'name' => 'Bronze',
				'amount' => '$200 to $499',
				'description' => 'Named on this page
A thank-you post across our social channels',
				'order' => 3,
			),
			array(
				'slug' => 'snowflake',
				'name' => 'Snowflake',
				'amount' => 'Personal donation, any amount',
				'description' => 'Named on this page
A thank-you post across our social channels',
				'order' => 4,
			),
		),
		'results' => array(
			array(
				'slug' => 'decode-roanoke-qualifier',
				'title' => 'Roanoke qualifier',
				'game' => 'DECODE',
				'years' => '2025-2026',
				'note' => 'Results for this season are being compiled.',
				'awards' => '',
				'order' => 0,
			),
			array(
				'slug' => 'decode-moorefield-qualifier-west-virginia',
				'title' => 'Moorefield qualifier, West Virginia',
				'game' => 'DECODE',
				'years' => '2025-2026',
				'note' => 'Results for this season are being compiled.',
				'awards' => '',
				'order' => 1,
			),
			array(
				'slug' => 'decode-virginia-state-championship',
				'title' => 'Virginia state championship',
				'game' => 'DECODE',
				'years' => '2025-2026',
				'note' => 'Results for this season are being compiled.',
				'awards' => '',
				'order' => 2,
			),
			array(
				'slug' => 'powerplay-chs-va-mechanicsville-qualifier-2',
				'title' => 'CHS-VA Mechanicsville qualifier 2',
				'game' => 'POWERPLAY',
				'years' => '2022-2023',
				'note' => '',
				'awards' => 'Connect Award, 2nd place
Control Award sponsored by Arm Inc., 3rd place',
				'order' => 0,
			),
			array(
				'slug' => 'powerplay-chs-va-harrisonburg-qualifier-2',
				'title' => 'CHS-VA Harrisonburg qualifier 2',
				'game' => 'POWERPLAY',
				'years' => '2022-2023',
				'note' => '',
				'awards' => 'Innovate Award sponsored by Raytheon Technologies, 2nd place',
				'order' => 1,
			),
			array(
				'slug' => 'powerplay-chs-va-herndon-qualifier',
				'title' => 'CHS-VA Herndon qualifier',
				'game' => 'POWERPLAY',
				'years' => '2022-2023',
				'note' => '',
				'awards' => 'Winning alliance, captain',
				'order' => 2,
			),
			array(
				'slug' => 'powerplay-chesapeake-ftc-championship-violet-division',
				'title' => 'Chesapeake FTC Championship, Violet Division',
				'game' => 'POWERPLAY',
				'years' => '2022-2023',
				'note' => '',
				'awards' => 'Connect Award, 3rd place
Promote Award, 3rd place
Violet Division winning alliance, second team selected
Finalist alliance, second team selected',
				'order' => 3,
			),
			array(
				'slug' => 'skystone-oakton-qualifier',
				'title' => 'Oakton qualifier',
				'game' => 'SKYSTONE',
				'years' => '2019-2020',
				'note' => '',
				'awards' => 'Motivate Award
Robot Design, 2nd place
Alliance finalist',
				'order' => 0,
			),
			array(
				'slug' => 'skystone-centreville-qualifier',
				'title' => 'Centreville qualifier',
				'game' => 'SKYSTONE',
				'years' => '2019-2020',
				'note' => '',
				'awards' => 'Inspire Award, qualified for states
Ranked 1st, won all five qualification matches
Elimination finalist
Control Award, 2nd place
Design Award, 3rd place',
				'order' => 1,
			),
			array(
				'slug' => 'skystone-dc-qualifier-maryland',
				'title' => 'DC qualifier, Maryland',
				'game' => 'SKYSTONE',
				'years' => '2019-2020',
				'note' => '',
				'awards' => 'Won the finals with Robot Uprising 14604 and Innovotics 8702
Think Award
Control Award, 2nd place
Connect Award, 3rd place
Advanced to Maryland states',
				'order' => 2,
			),
			array(
				'slug' => 'skystone-virginia-state-championship',
				'title' => 'Virginia state championship',
				'game' => 'SKYSTONE',
				'years' => '2019-2020',
				'note' => '',
				'awards' => '',
				'order' => 3,
			),
			array(
				'slug' => 'skystone-maryland-state-championship',
				'title' => 'Maryland state championship',
				'game' => 'SKYSTONE',
				'years' => '2019-2020',
				'note' => '',
				'awards' => 'Second state appearance of the season',
				'order' => 4,
			),
			array(
				'slug' => 'rover-ruckus-reston-at-centreville-regional-qualifier',
				'title' => 'Reston at Centreville regional qualifier',
				'game' => 'ROVER RUCKUS',
				'years' => '2018-2019',
				'note' => '',
				'awards' => 'Semi-finalists
Highest team score of the event, 322 points
Highest individual score of the event, 200 points
Connect Award, 1st place
Collins Aerospace Innovate Award, 2nd place
Control Award, 3rd place
Inspire Award, 3rd place
One of three teams advancing to the state championship',
				'order' => 0,
			),
			array(
				'slug' => 'rover-ruckus-virginia-state-championship-kamen-division',
				'title' => 'Virginia state championship, Kamen Division',
				'game' => 'ROVER RUCKUS',
				'years' => '2018-2019',
				'note' => '',
				'awards' => 'First pick of the first alliance
Divisional finalists
Highest score of the event, 400 points',
				'order' => 1,
			),
			array(
				'slug' => 'relic-recovery-shenandoah-qualifier',
				'title' => 'Shenandoah qualifier',
				'game' => 'RELIC RECOVERY',
				'years' => '2017-2018',
				'note' => '',
				'awards' => 'Winning alliance
Control Award',
				'order' => 0,
			),
			array(
				'slug' => 'relic-recovery-heritage-high-school-regional',
				'title' => 'Heritage High School regional',
				'game' => 'RELIC RECOVERY',
				'years' => '2017-2018',
				'note' => '',
				'awards' => 'Control Award, 1st place
Motivate Award, 2nd place
Inspire Award, 2nd place
Connect Award, 3rd place
Won four of five qualification matches
Fourth place in the finals',
				'order' => 1,
			),
			array(
				'slug' => 'relic-recovery-virginia-state-championship-richmond',
				'title' => 'Virginia state championship, Richmond',
				'game' => 'RELIC RECOVERY',
				'years' => '2017-2018',
				'note' => '',
				'awards' => 'Semi-finalists
Ranked 10th with a 3-2-0 record',
				'order' => 2,
			),
		),
		'shelves' => array(
			array(
				'slug' => 'available-now',
				'name' => 'Available now',
				'description' => 'Published, working and free. No account needed.',
				'order' => 0,
			),
		),
		'resources' => array(
			array(
				'slug' => 'pit-design-interactive-3d-model',
				'title' => 'Pit design, interactive 3D model',
				'shelf' => 'available-now',
				'season' => '2026-2027',
				'kind' => 'Web',
				'file' => 'https://absolutezero-pit.vercel.app',
				'size' => '',
				'external' => true,
				'order' => 0,
			),
			array(
				'slug' => 'robo-reach-match-score-predictor',
				'title' => 'Robo Reach, match score predictor',
				'shelf' => 'available-now',
				'season' => 'Every season',
				'kind' => 'Web',
				'file' => 'https://roboreach-eight.vercel.app',
				'size' => '',
				'external' => true,
				'order' => 1,
			),
		),
	);
}
